# Site settings
baseURL = "http://www.roberttillotson.com/"
languageCode = "en-US"
title = "Robert Tillotson - Digital Nomad - Insurance - Real Estate - Austin , Marfa , New Orleans"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-114903806-1"

# Copyright
copyright = "&copy;2019 population2.com"

[params]

  # Metadata for search engines and social sharing
  author = "Robert Tillotson"
  description = "Robert Tillotson - Digital Nomad - Insurance - Real Estate - Austin , Marfa , New Orleans"
  shareImage = "images/social.jpg"
  twitterHandle = "tilloglobe"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/bg.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "#"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "AirBNB"
        url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Global Health Benefit"
        url = "#"

      [[params.links.list3.link]]
        text = "Rancho Estrella Holdings"
        url = "#"

      [[params.links.list3.link]]
        text = "Consulting Services"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split